global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'flink-taskmanager'
    metrics_path: /
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'taskmanager:9249'
  - job_name: 'flink-jobmanager'
    metrics_path: /
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'jobmanager:9249'